import Image from 'next/image';
import Link from 'next/link';
export default function Home(){return <>
<section className="hero"><Image src="/images/hero.webp" alt="Szklane płytki i zwierciadła oświetlone ciepłym promieniem" fill priority className="hero-image" sizes="100vw"/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow light">GRA LOGICZNA ONLINE · ZA DARMO</div><h1>Zobacz, dokąd<br/><em>prowadzi światło.</em></h1><p>Obracaj zwierciadła. Znajdź drogę dla promienia. Rozwiązuj krótkie zagadki, które nagradzają spostrzegawczość.</p><div className="hero-buttons"><Link href="/gra" className="btn primary">Zagraj teraz <span>↗</span></Link><Link href="/jak-grac" className="btn ghost">Poznaj zasady</Link></div><div className="hero-caption"><span>✦</span> 3 autorskie poziomy <i/> Bez konta <i/> Na telefonie i komputerze</div></div></section>
<section className="intro section"><div className="section-heading"><span className="eyebrow">PROSTA ZASADA. WIELE MOŻLIWOŚCI.</span><h2>Jedno kliknięcie<br/>zmienia cały bieg gry.</h2></div><div className="intro-copy"><p>Każde zwierciadło odbija promień pod innym kątem. Obróć je, obserwuj nową trasę światła i krok po kroku doprowadź je do celu.</p><Link className="text-link" href="/gra">Wejdź na planszę <span>→</span></Link></div></section>
<section className="feature-grid section"><div className="feature-card image-card"><Image src="/images/mirrors.webp" alt="Układ zwierciadeł i świetlnej ścieżki na granatowej planszy" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div className="feature-card content-card"><span className="eyebrow">TWOJA CHWILA SKUPIENIA</span><h2>Gra, która pozwala myśleć po swojemu.</h2><p>Nie ma zegara ani presji. Testuj pomysły, wróć do początku jednym przyciskiem albo podejrzyj rozwiązanie, gdy potrzebujesz wskazówki.</p><div className="mini-features"><div><strong>01</strong><span>Obserwuj promień</span></div><div><strong>02</strong><span>Obracaj zwierciadła</span></div><div><strong>03</strong><span>Rozświetl cel</span></div></div><Link className="btn dark" href="/gra">Wybierz poziom <span>↗</span></Link></div></section>
<section className="benefits section"><div><span className="eyebrow">DLACZEGO WARTO SPRÓBOWAĆ?</span><h2>Krótka gra.<br/>Dużo satysfakcji.</h2></div><div className="benefit-list"><article><span>✧</span><div><h3>Od razu do gry</h3><p>Otwórz stronę i zacznij. Nie potrzebujesz konta, pobierania ani instrukcji na kilka stron.</p></div></article><article><span>◇</span><div><h3>Autorskie układy</h3><p>Trzy plansze prowadzą od pierwszego odbicia do prawdziwego świetlnego labiryntu.</p></div></article><article><span>↗</span><div><h3>Twój rytm</h3><p>Bez limitu czasu. Graj na komputerze lub telefonie i wracaj do ukończonych plansz.</p></div></article></div></section>
<section className="last-cta section"><Image src="/images/prism.webp" alt="Szklany pryzmat rozszczepiający światło" fill sizes="100vw"/><div className="last-overlay"/><div className="last-content"><span className="eyebrow light">GOTOWY NA PIERWSZE ODBICIE?</span><h2>Znajdź drogę<br/>dla światła.</h2><Link className="btn primary" href="/gra">Przejdź do gry <span>↗</span></Link></div></section>
</>}
